### Use conda

In [61]:
import pandas as pd
import numpy as np

# Set pandas to display all columns
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('NSDUH_2023_Cleaned.csv')
df

,CATAGE,EDUHIGHCAT,EDUSCHLGO,EDUSCHGRD2,UADPAID,UADMONY,UADBWHO,UADPLACE,UADBUND,TOBCIGONL,...,TOBALCYR,TOBALCMN,YELSTGRD,YERLFRND,AVGGRADE,SMIPY,AMIPY,ATXMDEYR,MHTRTPY,CAMHPROB
0,1,5,1,3,3.0,3.0,3.0,4.0,3.0,4,...,0,0,1,3,2.0,NaN,NaN,NaN,0,99
1,2,2,2,99,1.0,1.0,1.0,2.0,3.0,3,...,1,1,99,99,NaN,0.0,0.0,NaN,0,2
2,3,4,2,99,3.0,3.0,3.0,4.0,3.0,4,...,1,1,99,99,NaN,0.0,0.0,NaN,0,1
3,3,4,2,99,3.0,3.0,3.0,4.0,3.0,4,...,1,1,99,99,NaN,0.0,0.0,NaN,0,2
4,1,5,1,6,3.0,3.0,3.0,4.0,3.0,4,...,0,0,2,1,2.0,NaN,NaN,NaN,0,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30258,2,3,1,10,3.0,3.0,3.0,4.0,3.0,4,...,0,0,99,99,NaN,0.0,1.0,NaN,0,2
30259,2,3,1,10,3.0,3.0,3.0,4.0,3.0,4,...,0,0,99,99,NaN,0.0,0.0,NaN,0,2
30260,3,4,2,99,3.0,3.0,3.0,4.0,3.0,4,...,1,1,99,99,NaN,0.0,0.0,1.0,1,1
30261,2,2,2,99,3.0,3.0,3.0,4.0,3.0,4,...,1,1,99,99,NaN,0.0,1.0,1.0,1,1
30262,2,2,2,99,3.0,3.0,3.0,4.0,3.0,4,...,0,0,99,99,NaN,0.0,0.0,NaN,0,2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30263 entries, 0 to 30262
Data columns (total 42 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CATAGE       30263 non-null  int64
 1   EDUHIGHCAT   30263 non-null  int64
 2   EDUSCHLGO    30263 non-null  int64
 3   EDUSCHGRD2   30263 non-null  int64
 4   UADPAID      29975 non-null  float64
 5   UADMONY      29963 non-null  float64
 6   UADBWHO      29962 non-null  float64
 7   UADPLACE     29962 non-null  float64
 8   UADBUND      29962 non-null  float64
 9   TOBCIGONL    30263 non-null  int64
 10  TOBFLAG      30263 non-null  int64
 11  TOBYR        30263 non-null  int64
 12  TOBMON       30263 non-null  int64
 13  NICVAPFLAG   30263 non-null  int64
 14  NICVAPYR     30263 non-null  int64
 15  NICVAPMON    30263 non-null  int64
 16  TOBVNICFLAG  30263 non-null  int64
 17  TOBVNICYR    30263 non-null  int64
 18  TOBVNICMON   30263 non-null  int64
 19  TOBVAPONL2   30263 non-null  int64
 20  TOBCIGVAP2   30263 non-null  int64
 21  COCYR        30263 non-null  int64
 22  COCMON       30263 non-null  int64
 23  HERPNRYR     30263 non-null  int64
 24  ILLFLAG      30263 non-null  int64
 25  ILLMON       30263 non-null  int64
 26  ILLEMYR      30263 non-null  int64
 27  CDUFLAG      30263 non-null  int64
 28  DCIGMON      30263 non-null  int64
 29  BNGDRKMON    30263 non-null  int64
 30  HVYDRKMON    30263 non-null  int64
 31  TOBALCFLG    30263 non-null  int64
 32  TOBALCYR     30263 non-null  int64
 33  TOBALCMN     30263 non-null  int64
 34  YELSTGRD     30263 non-null  int64
 35  YERLFRND     30263 non-null  int64
 36  AVGGRADE     8731 non-null   float64
 37  SMIPY        20036 non-null  float64
 38  AMIPY        20036 non-null  float64
 39  ATXMDEYR     4874 non-null   float64
 40  MHTRTPY      30263 non-null  int64
 41  CAMHPROB     30263 non-null  int64
dtypes: float64(9), int64(33)
memory usage: 9.7 MB

In [5]:
columns = df.columns
columns

Index(['CATAGE', 'EDUHIGHCAT', 'EDUSCHLGO', 'EDUSCHGRD2', 'UADPAID', 'UADMONY',
       'UADBWHO', 'UADPLACE', 'UADBUND', 'TOBCIGONL', 'TOBFLAG', 'TOBYR',
       'TOBMON', 'NICVAPFLAG', 'NICVAPYR', 'NICVAPMON', 'TOBVNICFLAG',
       'TOBVNICYR', 'TOBVNICMON', 'TOBVAPONL2', 'TOBCIGVAP2', 'COCYR',
       'COCMON', 'HERPNRYR', 'ILLFLAG', 'ILLMON', 'ILLEMYR', 'CDUFLAG',
       'DCIGMON', 'BNGDRKMON', 'HVYDRKMON', 'TOBALCFLG', 'TOBALCYR',
       'TOBALCMN', 'YELSTGRD', 'YERLFRND', 'AVGGRADE', 'SMIPY', 'AMIPY',
       'ATXMDEYR', 'MHTRTPY', 'CAMHPROB'],
      dtype='object')

In [18]:
use_columns = [col for col in df.columns if sorted(df[col].unique()) == [0, 1]]

In [19]:
use_columns

['TOBFLAG',
 'TOBYR',
 'TOBMON',
 'NICVAPFLAG',
 'NICVAPYR',
 'NICVAPMON',
 'TOBVNICFLAG',
 'TOBVNICYR',
 'TOBVNICMON',
 'COCYR',
 'COCMON',
 'ILLFLAG',
 'ILLMON',
 'ILLEMYR',
 'CDUFLAG',
 'DCIGMON',
 'BNGDRKMON',
 'HVYDRKMON',
 'TOBALCFLG',
 'TOBALCYR',
 'TOBALCMN',
 'MHTRTPY']

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30263 entries, 0 to 30262
Data columns (total 42 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CATAGE       30263 non-null  int64
 1   EDUHIGHCAT   30263 non-null  int64
 2   EDUSCHLGO    30263 non-null  int64
 3   EDUSCHGRD2   30263 non-null  int64
 4   UADPAID      29975 non-null  float64
 5   UADMONY      29963 non-null  float64
 6   UADBWHO      29962 non-null  float64
 7   UADPLACE     29962 non-null  float64
 8   UADBUND      29962 non-null  float64
 9   TOBCIGONL    30263 non-null  int64
 10  TOBFLAG      30263 non-null  int64
 11  TOBYR        30263 non-null  int64
 12  TOBMON       30263 non-null  int64
 13  NICVAPFLAG   30263 non-null  int64
 14  NICVAPYR     30263 non-null  int64
 15  NICVAPMON    30263 non-null  int64
 16  TOBVNICFLAG  30263 non-null  int64
 17  TOBVNICYR    30263 non-null  int64
 18  TOBVNICMON   30263 non-null  int64
 19  TOBVAPONL2   30263 non-null  int64
 20  TOBCIGVAP2   30263 non-null  int64
 21  COCYR        30263 non-null  int64
 22  COCMON       30263 non-null  int64
 23  HERPNRYR     30263 non-null  int64
 24  ILLFLAG      30263 non-null  int64
 25  ILLMON       30263 non-null  int64
 26  ILLEMYR      30263 non-null  int64
 27  CDUFLAG      30263 non-null  int64
 28  DCIGMON      30263 non-null  int64
 29  BNGDRKMON    30263 non-null  int64
 30  HVYDRKMON    30263 non-null  int64
 31  TOBALCFLG    30263 non-null  int64
 32  TOBALCYR     30263 non-null  int64
 33  TOBALCMN     30263 non-null  int64
 34  YELSTGRD     30263 non-null  int64
 35  YERLFRND     30263 non-null  int64
 36  AVGGRADE     8731 non-null   float64
 37  SMIPY        20036 non-null  float64
 38  AMIPY        20036 non-null  float64
 39  ATXMDEYR     4874 non-null   float64
 40  MHTRTPY      30263 non-null  int64
 41  CAMHPROB     30263 non-null  int64
dtypes: float64(9), int64(33)
memory usage: 9.7 MB

In [20]:
diag_columns = ['SMIPY', 'AMIPY', 'ATXMDEYR', 'MHTRTPY']
diag_columns

['SMIPY', 'AMIPY', 'ATXMDEYR', 'MHTRTPY']

In [17]:
for col in df.columns:
    print('**'*25)
    print(f'Col {col} has values {df[col].unique()}')

**************************************************
Col CATAGE has values [1 2 3]
**************************************************
Col EDUHIGHCAT has values [5 2 4 1 3]
**************************************************
Col EDUSCHLGO has values [ 1  2 98 97 94 85 11]
**************************************************
Col EDUSCHGRD2 has values [ 3 99  6 98  2  5  4 10  7  8 11  9  1]
**************************************************
Col UADPAID has values [ 3.  1.  2. nan]
**************************************************
Col UADMONY has values [ 3.  1. nan  2.]
**************************************************
Col UADBWHO has values [ 3.  1. nan  2.]
**************************************************
Col UADPLACE has values [ 4.  2. nan  1.  3.]
**************************************************
Col UADBUND has values [ 3. nan  2.  1.]
**************************************************
Col TOBCIGONL has values [4 3 1 2]
**************************************************
Col TOBFLAG has values [0 1]
**************************************************
Col TOBYR has values [0 1]
**************************************************
Col TOBMON has values [0 1]
**************************************************
Col NICVAPFLAG has values [0 1]
**************************************************
Col NICVAPYR has values [0 1]
**************************************************
Col NICVAPMON has values [0 1]
**************************************************
Col TOBVNICFLAG has values [0 1]
**************************************************
Col TOBVNICYR has values [0 1]
**************************************************
Col TOBVNICMON has values [0 1]
**************************************************
Col TOBVAPONL2 has values [4 2 3 1]
**************************************************
Col TOBCIGVAP2 has values [4 3 1 2]
**************************************************
Col COCYR has values [0 1]
**************************************************
Col COCMON has values [0 1]
**************************************************
Col HERPNRYR has values [4 2 3 1]
**************************************************
Col ILLFLAG has values [0 1]
**************************************************
Col ILLMON has values [0 1]
**************************************************
Col ILLEMYR has values [0 1]
**************************************************
Col CDUFLAG has values [0 1]
**************************************************
Col DCIGMON has values [0 1]
**************************************************
Col BNGDRKMON has values [0 1]
**************************************************
Col HVYDRKMON has values [0 1]
**************************************************
Col TOBALCFLG has values [0 1]
**************************************************
Col TOBALCYR has values [0 1]
**************************************************
Col TOBALCMN has values [0 1]
**************************************************
Col YELSTGRD has values [ 1 99  2  5  3  4 94 98 97 85]
**************************************************
Col YERLFRND has values [ 3 99  1  2  4 94 97 85 98]
**************************************************
Col AVGGRADE has values [ 2. nan  1.]
**************************************************
Col SMIPY has values [nan  0.  1.]
**************************************************
Col AMIPY has values [nan  0.  1.]
**************************************************
Col ATXMDEYR has values [nan  0.  1.]
**************************************************
Col MHTRTPY has values [0 1]
**************************************************
Col CAMHPROB has values [99  2  1 85 98 97 94]

In [24]:
for col in use_columns:
    print('**'*25)
    print(f'Col {col} has values {df[col].unique()}')

**************************************************
Col TOBFLAG has values [0 1]
**************************************************
Col TOBYR has values [0 1]
**************************************************
Col TOBMON has values [0 1]
**************************************************
Col NICVAPFLAG has values [0 1]
**************************************************
Col NICVAPYR has values [0 1]
**************************************************
Col NICVAPMON has values [0 1]
**************************************************
Col TOBVNICFLAG has values [0 1]
**************************************************
Col TOBVNICYR has values [0 1]
**************************************************
Col TOBVNICMON has values [0 1]
**************************************************
Col COCYR has values [0 1]
**************************************************
Col COCMON has values [0 1]
**************************************************
Col ILLFLAG has values [0 1]
**************************************************
Col ILLMON has values [0 1]
**************************************************
Col ILLEMYR has values [0 1]
**************************************************
Col CDUFLAG has values [0 1]
**************************************************
Col DCIGMON has values [0 1]
**************************************************
Col BNGDRKMON has values [0 1]
**************************************************
Col HVYDRKMON has values [0 1]
**************************************************
Col TOBALCFLG has values [0 1]
**************************************************
Col TOBALCYR has values [0 1]
**************************************************
Col TOBALCMN has values [0 1]
**************************************************
Col MHTRTPY has values [0 1]

In [33]:
df['ATXMDEYR'].value_counts(dropna=False)

ATXMDEYR
NaN    25389
0.0     2533
1.0     2341
Name: count, dtype: int64

In [36]:
for col in diag_columns:
    print('**'*25)
    print(f'Col {col} has values {df[col].unique()}')
    print(df[col].value_counts(dropna=False))

**************************************************
Col SMIPY has values [nan  0.  1.]
SMIPY
0.0    17958
NaN    10227
1.0     2078
Name: count, dtype: int64
**************************************************
Col AMIPY has values [nan  0.  1.]
AMIPY
0.0    13210
NaN    10227
1.0     6826
Name: count, dtype: int64
**************************************************
Col ATXMDEYR has values [nan  0.  1.]
ATXMDEYR
NaN    25389
0.0     2533
1.0     2341
Name: count, dtype: int64
**************************************************
Col MHTRTPY has values [0 1]
MHTRTPY
0    21432
1     8831
Name: count, dtype: int64

In [44]:
for col1 in use_columns:
    for col2 in diag_columns:
        df[f'{col1}_{col2}'] = df.apply(
            lambda row: np.nan if pd.isna(row[col1]) or pd.isna(row[col2]) else int(row[col1] == 1 and row[col2] == 1),
            axis=1
        )

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30263 entries, 0 to 30262
Columns: 130 entries, CATAGE to MHTRTPY_MHTRTPY
dtypes: float64(75), int64(55)
memory usage: 30.0 MB

In [48]:
df.columns

Index(['CATAGE', 'EDUHIGHCAT', 'EDUSCHLGO', 'EDUSCHGRD2', 'UADPAID', 'UADMONY',
       'UADBWHO', 'UADPLACE', 'UADBUND', 'TOBCIGONL',
       ...
       'TOBALCYR_ATXMDEYR', 'TOBALCYR_MHTRTPY', 'TOBALCMN_SMIPY',
       'TOBALCMN_AMIPY', 'TOBALCMN_ATXMDEYR', 'TOBALCMN_MHTRTPY',
       'MHTRTPY_SMIPY', 'MHTRTPY_AMIPY', 'MHTRTPY_ATXMDEYR',
       'MHTRTPY_MHTRTPY'],
      dtype='object', length=130)

In [50]:
comb_columns = [col for col in df.columns if '_' in col]
comb_columns

['TOBFLAG_SMIPY',
 'TOBFLAG_AMIPY',
 'TOBFLAG_ATXMDEYR',
 'TOBFLAG_MHTRTPY',
 'TOBYR_SMIPY',
 'TOBYR_AMIPY',
 'TOBYR_ATXMDEYR',
 'TOBYR_MHTRTPY',
 'TOBMON_SMIPY',
 'TOBMON_AMIPY',
 'TOBMON_ATXMDEYR',
 'TOBMON_MHTRTPY',
 'NICVAPFLAG_SMIPY',
 'NICVAPFLAG_AMIPY',
 'NICVAPFLAG_ATXMDEYR',
 'NICVAPFLAG_MHTRTPY',
 'NICVAPYR_SMIPY',
 'NICVAPYR_AMIPY',
 'NICVAPYR_ATXMDEYR',
 'NICVAPYR_MHTRTPY',
 'NICVAPMON_SMIPY',
 'NICVAPMON_AMIPY',
 'NICVAPMON_ATXMDEYR',
 'NICVAPMON_MHTRTPY',
 'TOBVNICFLAG_SMIPY',
 'TOBVNICFLAG_AMIPY',
 'TOBVNICFLAG_ATXMDEYR',
 'TOBVNICFLAG_MHTRTPY',
 'TOBVNICYR_SMIPY',
 'TOBVNICYR_AMIPY',
 'TOBVNICYR_ATXMDEYR',
 'TOBVNICYR_MHTRTPY',
 'TOBVNICMON_SMIPY',
 'TOBVNICMON_AMIPY',
 'TOBVNICMON_ATXMDEYR',
 'TOBVNICMON_MHTRTPY',
 'COCYR_SMIPY',
 'COCYR_AMIPY',
 'COCYR_ATXMDEYR',
 'COCYR_MHTRTPY',
 'COCMON_SMIPY',
 'COCMON_AMIPY',
 'COCMON_ATXMDEYR',
 'COCMON_MHTRTPY',
 'ILLFLAG_SMIPY',
 'ILLFLAG_AMIPY',
 'ILLFLAG_ATXMDEYR',
 'ILLFLAG_MHTRTPY',
 'ILLMON_SMIPY',
 'ILLMON_AMIPY',
 'ILLMON_ATXMDEYR',
 'ILLMON_MHTRTPY',
 'ILLEMYR_SMIPY',
 'ILLEMYR_AMIPY',
 'ILLEMYR_ATXMDEYR',
 'ILLEMYR_MHTRTPY',
 'CDUFLAG_SMIPY',
 'CDUFLAG_AMIPY',
 'CDUFLAG_ATXMDEYR',
 'CDUFLAG_MHTRTPY',
 'DCIGMON_SMIPY',
 'DCIGMON_AMIPY',
 'DCIGMON_ATXMDEYR',
 'DCIGMON_MHTRTPY',
 'BNGDRKMON_SMIPY',
 'BNGDRKMON_AMIPY',
 'BNGDRKMON_ATXMDEYR',
 'BNGDRKMON_MHTRTPY',
 'HVYDRKMON_SMIPY',
 'HVYDRKMON_AMIPY',
 'HVYDRKMON_ATXMDEYR',
 'HVYDRKMON_MHTRTPY',
 'TOBALCFLG_SMIPY',
 'TOBALCFLG_AMIPY',
 'TOBALCFLG_ATXMDEYR',
 'TOBALCFLG_MHTRTPY',
 'TOBALCYR_SMIPY',
 'TOBALCYR_AMIPY',
 'TOBALCYR_ATXMDEYR',
 'TOBALCYR_MHTRTPY',
 'TOBALCMN_SMIPY',
 'TOBALCMN_AMIPY',
 'TOBALCMN_ATXMDEYR',
 'TOBALCMN_MHTRTPY',
 'MHTRTPY_SMIPY',
 'MHTRTPY_AMIPY',
 'MHTRTPY_ATXMDEYR',
 'MHTRTPY_MHTRTPY']

In [51]:
for col in comb_columns:
    print('**'*25)
    print(f'Col {col} has values {df[col].unique()}')
    print(df[col].value_counts(dropna=False))

**************************************************
Col TOBFLAG_SMIPY has values [nan  0.  1.]
TOBFLAG_SMIPY
0.0    18719
NaN    10227
1.0     1317
Name: count, dtype: int64
**************************************************
Col TOBFLAG_AMIPY has values [nan  0.  1.]
TOBFLAG_AMIPY
0.0    16106
NaN    10227
1.0     3930
Name: count, dtype: int64
**************************************************
Col TOBFLAG_ATXMDEYR has values [nan  0.  1.]
TOBFLAG_ATXMDEYR
NaN    25389
0.0     3539
1.0     1335
Name: count, dtype: int64
**************************************************
Col TOBFLAG_MHTRTPY has values [0 1]
TOBFLAG_MHTRTPY
0    26743
1     3520
Name: count, dtype: int64
**************************************************
Col TOBYR_SMIPY has values [nan  0.  1.]
TOBYR_SMIPY
0.0    19273
NaN    10227
1.0      763
Name: count, dtype: int64
**************************************************
Col TOBYR_AMIPY has values [nan  0.  1.]
TOBYR_AMIPY
0.0    17850
NaN    10227
1.0     2186
Name: count, dtype: int64
**************************************************
Col TOBYR_ATXMDEYR has values [nan  0.  1.]
TOBYR_ATXMDEYR
NaN    25389
0.0     4167
1.0      707
Name: count, dtype: int64
**************************************************
Col TOBYR_MHTRTPY has values [0 1]
TOBYR_MHTRTPY
0    28399
1     1864
Name: count, dtype: int64
**************************************************
Col TOBMON_SMIPY has values [nan  0.  1.]
TOBMON_SMIPY
0.0    19519
NaN    10227
1.0      517
Name: count, dtype: int64
**************************************************
Col TOBMON_AMIPY has values [nan  0.  1.]
TOBMON_AMIPY
0.0    18550
NaN    10227
1.0     1486
Name: count, dtype: int64
**************************************************
Col TOBMON_ATXMDEYR has values [nan  0.  1.]
TOBMON_ATXMDEYR
NaN    25389
0.0     4433
1.0      441
Name: count, dtype: int64
**************************************************
Col TOBMON_MHTRTPY has values [0 1]
TOBMON_MHTRTPY
0    29092
1     1171
Name: count, dtype: int64
**************************************************
Col NICVAPFLAG_SMIPY has values [nan  0.  1.]
NICVAPFLAG_SMIPY
0.0    18745
NaN    10227
1.0     1291
Name: count, dtype: int64
**************************************************
Col NICVAPFLAG_AMIPY has values [nan  0.  1.]
NICVAPFLAG_AMIPY
0.0    16181
NaN    10227
1.0     3855
Name: count, dtype: int64
**************************************************
Col NICVAPFLAG_ATXMDEYR has values [nan  0.  1.]
NICVAPFLAG_ATXMDEYR
NaN    25389
0.0     3568
1.0     1306
Name: count, dtype: int64
**************************************************
Col NICVAPFLAG_MHTRTPY has values [0 1]
NICVAPFLAG_MHTRTPY
0    26416
1     3847
Name: count, dtype: int64
**************************************************
Col NICVAPYR_SMIPY has values [nan  0.  1.]
NICVAPYR_SMIPY
0.0    19158
NaN    10227
1.0      878
Name: count, dtype: int64
**************************************************
Col NICVAPYR_AMIPY has values [nan  0.  1.]
NICVAPYR_AMIPY
0.0    17517
NaN    10227
1.0     2519
Name: count, dtype: int64
**************************************************
Col NICVAPYR_ATXMDEYR has values [nan  0.  1.]
NICVAPYR_ATXMDEYR
NaN    25389
0.0     4053
1.0      821
Name: count, dtype: int64
**************************************************
Col NICVAPYR_MHTRTPY has values [0 1]
NICVAPYR_MHTRTPY
0    27702
1     2561
Name: count, dtype: int64
**************************************************
Col NICVAPMON_SMIPY has values [nan  0.  1.]
NICVAPMON_SMIPY
0.0    19360
NaN    10227
1.0      676
Name: count, dtype: int64
**************************************************
Col NICVAPMON_AMIPY has values [nan  0.  1.]
NICVAPMON_AMIPY
0.0    18142
NaN    10227
1.0     1894
Name: count, dtype: int64
**************************************************
Col NICVAPMON_ATXMDEYR has values [nan  0.  1.]
NICVAPMON_ATXMDEYR
NaN    25389
0.0     4254
1.0      620
Name: count, dtype: int64
**************************************************
Col NICVAPMON_MHTRTPY has values [0 1]
NICVAPMON_MHTRTPY
0    28479
1     1784
Name: count, dtype: int64
**************************************************
Col TOBVNICFLAG_SMIPY has values [nan  0.  1.]
TOBVNICFLAG_SMIPY
0.0    18515
NaN    10227
1.0     1521
Name: count, dtype: int64
**************************************************
Col TOBVNICFLAG_AMIPY has values [nan  0.  1.]
TOBVNICFLAG_AMIPY
0.0    15379
NaN    10227
1.0     4657
Name: count, dtype: int64
**************************************************
Col TOBVNICFLAG_ATXMDEYR has values [nan  0.  1.]
TOBVNICFLAG_ATXMDEYR
NaN    25389
0.0     3294
1.0     1580
Name: count, dtype: int64
**************************************************
Col TOBVNICFLAG_MHTRTPY has values [0 1]
TOBVNICFLAG_MHTRTPY
0    25630
1     4633
Name: count, dtype: int64
**************************************************
Col TOBVNICYR_SMIPY has values [nan  0.  1.]
TOBVNICYR_SMIPY
0.0    18966
NaN    10227
1.0     1070
Name: count, dtype: int64
**************************************************
Col TOBVNICYR_AMIPY has values [nan  0.  1.]
TOBVNICYR_AMIPY
0.0    16863
NaN    10227
1.0     3173
Name: count, dtype: int64
**************************************************
Col TOBVNICYR_ATXMDEYR has values [nan  0.  1.]
TOBVNICYR_ATXMDEYR
NaN    25389
0.0     3841
1.0     1033
Name: count, dtype: int64
**************************************************
Col TOBVNICYR_MHTRTPY has values [0 1]
TOBVNICYR_MHTRTPY
0    27163
1     3100
Name: count, dtype: int64
**************************************************
Col TOBVNICMON_SMIPY has values [nan  0.  1.]
TOBVNICMON_SMIPY
0.0    19178
NaN    10227
1.0      858
Name: count, dtype: int64
**************************************************
Col TOBVNICMON_AMIPY has values [nan  0.  1.]
TOBVNICMON_AMIPY
0.0    17536
NaN    10227
1.0     2500
Name: count, dtype: int64
**************************************************
Col TOBVNICMON_ATXMDEYR has values [nan  0.  1.]
TOBVNICMON_ATXMDEYR
NaN    25389
0.0     4084
1.0      790
Name: count, dtype: int64
**************************************************
Col TOBVNICMON_MHTRTPY has values [0 1]
TOBVNICMON_MHTRTPY
0    28013
1     2250
Name: count, dtype: int64
**************************************************
Col COCYR_SMIPY has values [nan  0.  1.]
COCYR_SMIPY
0.0    19887
NaN    10227
1.0      149
Name: count, dtype: int64
**************************************************
Col COCYR_AMIPY has values [nan  0.  1.]
COCYR_AMIPY
0.0    19674
NaN    10227
1.0      362
Name: count, dtype: int64
**************************************************
Col COCYR_ATXMDEYR has values [nan  0.  1.]
COCYR_ATXMDEYR
NaN    25389
0.0     4749
1.0      125
Name: count, dtype: int64
**************************************************
Col COCYR_MHTRTPY has values [0 1]
COCYR_MHTRTPY
0    29970
1      293
Name: count, dtype: int64
**************************************************
Col COCMON_SMIPY has values [nan  0.  1.]
COCMON_SMIPY
0.0    19993
NaN    10227
1.0       43
Name: count, dtype: int64
**************************************************
Col COCMON_AMIPY has values [nan  0.  1.]
COCMON_AMIPY
0.0    19924
NaN    10227
1.0      112
Name: count, dtype: int64
**************************************************
Col COCMON_ATXMDEYR has values [nan  0.  1.]
COCMON_ATXMDEYR
NaN    25389
0.0     4848
1.0       26
Name: count, dtype: int64
**************************************************
Col COCMON_MHTRTPY has values [0 1]
COCMON_MHTRTPY
0    30181
1       82
Name: count, dtype: int64
**************************************************
Col ILLFLAG_SMIPY has values [nan  0.  1.]
ILLFLAG_SMIPY
0.0    18388
NaN    10227
1.0     1648
Name: count, dtype: int64
**************************************************
Col ILLFLAG_AMIPY has values [nan  0.  1.]
ILLFLAG_AMIPY
0.0    15104
NaN    10227
1.0     4932
Name: count, dtype: int64
**************************************************
Col ILLFLAG_ATXMDEYR has values [nan  0.  1.]
ILLFLAG_ATXMDEYR
NaN    25389
0.0     3103
1.0     1771
Name: count, dtype: int64
**************************************************
Col ILLFLAG_MHTRTPY has values [0 1]
ILLFLAG_MHTRTPY
0    25393
1     4870
Name: count, dtype: int64
**************************************************
Col ILLMON_SMIPY has values [nan  0.  1.]
ILLMON_SMIPY
0.0    19126
NaN    10227
1.0      910
Name: count, dtype: int64
**************************************************
Col ILLMON_AMIPY has values [nan  0.  1.]
ILLMON_AMIPY
0.0    17544
NaN    10227
1.0     2492
Name: count, dtype: int64
**************************************************
Col ILLMON_ATXMDEYR has values [nan  0.  1.]
ILLMON_ATXMDEYR
NaN    25389
0.0     3981
1.0      893
Name: count, dtype: int64
**************************************************
Col ILLMON_MHTRTPY has values [0 1]
ILLMON_MHTRTPY
0    27931
1     2332
Name: count, dtype: int64
**************************************************
Col ILLEMYR_SMIPY has values [nan  0.  1.]
ILLEMYR_SMIPY
0.0    19485
NaN    10227
1.0      551
Name: count, dtype: int64
**************************************************
Col ILLEMYR_AMIPY has values [nan  0.  1.]
ILLEMYR_AMIPY
0.0    18638
NaN    10227
1.0     1398
Name: count, dtype: int64
**************************************************
Col ILLEMYR_ATXMDEYR has values [nan  0.  1.]
ILLEMYR_ATXMDEYR
NaN    25389
0.0     4364
1.0      510
Name: count, dtype: int64
**************************************************
Col ILLEMYR_MHTRTPY has values [0 1]
ILLEMYR_MHTRTPY
0    28837
1     1426
Name: count, dtype: int64
**************************************************
Col CDUFLAG_SMIPY has values [nan  0.  1.]
CDUFLAG_SMIPY
0.0    19474
NaN    10227
1.0      562
Name: count, dtype: int64
**************************************************
Col CDUFLAG_AMIPY has values [nan  0.  1.]
CDUFLAG_AMIPY
0.0    18515
NaN    10227
1.0     1521
Name: count, dtype: int64
**************************************************
Col CDUFLAG_ATXMDEYR has values [nan  0.  1.]
CDUFLAG_ATXMDEYR
NaN    25389
0.0     4406
1.0      468
Name: count, dtype: int64
**************************************************
Col CDUFLAG_MHTRTPY has values [0 1]
CDUFLAG_MHTRTPY
0    29128
1     1135
Name: count, dtype: int64
**************************************************
Col DCIGMON_SMIPY has values [nan  0.  1.]
DCIGMON_SMIPY
0.0    19856
NaN    10227
1.0      180
Name: count, dtype: int64
**************************************************
Col DCIGMON_AMIPY has values [nan  0.  1.]
DCIGMON_AMIPY
0.0    19567
NaN    10227
1.0      469
Name: count, dtype: int64
**************************************************
Col DCIGMON_ATXMDEYR has values [nan  0.  1.]
DCIGMON_ATXMDEYR
NaN    25389
0.0     4729
1.0      145
Name: count, dtype: int64
**************************************************
Col DCIGMON_MHTRTPY has values [0 1]
DCIGMON_MHTRTPY
0    29950
1      313
Name: count, dtype: int64
**************************************************
Col BNGDRKMON_SMIPY has values [nan  0.  1.]
BNGDRKMON_SMIPY
0.0    19323
NaN    10227
1.0      713
Name: count, dtype: int64
**************************************************
Col BNGDRKMON_AMIPY has values [nan  0.  1.]
BNGDRKMON_AMIPY
0.0    17803
NaN    10227
1.0     2233
Name: count, dtype: int64
**************************************************
Col BNGDRKMON_ATXMDEYR has values [nan  0.  1.]
BNGDRKMON_ATXMDEYR
NaN    25389
0.0     4147
1.0      727
Name: count, dtype: int64
**************************************************
Col BNGDRKMON_MHTRTPY has values [0 1]
BNGDRKMON_MHTRTPY
0    28357
1     1906
Name: count, dtype: int64
**************************************************
Col HVYDRKMON_SMIPY has values [nan  0.  1.]
HVYDRKMON_SMIPY
0.0    19814
NaN    10227
1.0      222
Name: count, dtype: int64
**************************************************
Col HVYDRKMON_AMIPY has values [nan  0.  1.]
HVYDRKMON_AMIPY
0.0    19405
NaN    10227
1.0      631
Name: count, dtype: int64
**************************************************
Col HVYDRKMON_ATXMDEYR has values [nan  0.  1.]
HVYDRKMON_ATXMDEYR
NaN    25389
0.0     4689
1.0      185
Name: count, dtype: int64
**************************************************
Col HVYDRKMON_MHTRTPY has values [0 1]
HVYDRKMON_MHTRTPY
0    29770
1      493
Name: count, dtype: int64
**************************************************
Col TOBALCFLG_SMIPY has values [nan  0.  1.]
TOBALCFLG_SMIPY
0.0    18146
NaN    10227
1.0     1890
Name: count, dtype: int64
**************************************************
Col TOBALCFLG_AMIPY has values [nan  0.  1.]
TOBALCFLG_AMIPY
0.0    14028
NaN    10227
1.0     6008
Name: count, dtype: int64
**************************************************
Col TOBALCFLG_ATXMDEYR has values [nan  0.  1.]
TOBALCFLG_ATXMDEYR
NaN    25389
0.0     2775
1.0     2099
Name: count, dtype: int64
**************************************************
Col TOBALCFLG_MHTRTPY has values [0 1]
TOBALCFLG_MHTRTPY
0    24504
1     5759
Name: count, dtype: int64
**************************************************
Col TOBALCYR_SMIPY has values [nan  0.  1.]
TOBALCYR_SMIPY
0.0    18344
NaN    10227
1.0     1692
Name: count, dtype: int64
**************************************************
Col TOBALCYR_AMIPY has values [nan  0.  1.]
TOBALCYR_AMIPY
0.0    14585
NaN    10227
1.0     5451
Name: count, dtype: int64
**************************************************
Col TOBALCYR_ATXMDEYR has values [nan  0.  1.]
TOBALCYR_ATXMDEYR
NaN    25389
0.0     2986
1.0     1888
Name: count, dtype: int64
**************************************************
Col TOBALCYR_MHTRTPY has values [0 1]
TOBALCYR_MHTRTPY
0    25137
1     5126
Name: count, dtype: int64
**************************************************
Col TOBALCMN_SMIPY has values [nan  0.  1.]
TOBALCMN_SMIPY
0.0    18674
NaN    10227
1.0     1362
Name: count, dtype: int64
**************************************************
Col TOBALCMN_AMIPY has values [nan  0.  1.]
TOBALCMN_AMIPY
0.0    15687
NaN    10227
1.0     4349
Name: count, dtype: int64
**************************************************
Col TOBALCMN_ATXMDEYR has values [nan  0.  1.]
TOBALCMN_ATXMDEYR
NaN    25389
0.0     3384
1.0     1490
Name: count, dtype: int64
**************************************************
Col TOBALCMN_MHTRTPY has values [0 1]
TOBALCMN_MHTRTPY
0    26431
1     3832
Name: count, dtype: int64
**************************************************
Col MHTRTPY_SMIPY has values [nan  0.  1.]
MHTRTPY_SMIPY
0.0    18626
NaN    10227
1.0     1410
Name: count, dtype: int64
**************************************************
Col MHTRTPY_AMIPY has values [nan  0.  1.]
MHTRTPY_AMIPY
0.0    16474
NaN    10227
1.0     3562
Name: count, dtype: int64
**************************************************
Col MHTRTPY_ATXMDEYR has values [nan  0.  1.]
MHTRTPY_ATXMDEYR
NaN    25389
0.0     2751
1.0     2123
Name: count, dtype: int64
**************************************************
Col MHTRTPY_MHTRTPY has values [0 1]
MHTRTPY_MHTRTPY
0    21432
1     8831
Name: count, dtype: int64

In [52]:
# Compute correlation with Column1
correlation_matrix = df.corr()

In [53]:
correlation_matrix

,CATAGE,EDUHIGHCAT,EDUSCHLGO,EDUSCHGRD2,UADPAID,UADMONY,UADBWHO,UADPLACE,UADBUND,TOBCIGONL,...,TOBALCYR_ATXMDEYR,TOBALCYR_MHTRTPY,TOBALCMN_SMIPY,TOBALCMN_AMIPY,TOBALCMN_ATXMDEYR,TOBALCMN_MHTRTPY,MHTRTPY_SMIPY,MHTRTPY_AMIPY,MHTRTPY_ATXMDEYR,MHTRTPY_MHTRTPY
CATAGE,1.000000,-0.617111,0.051360,0.631581,0.085338,0.021670,0.010234,0.010293,0.004322,-0.211571,...,0.054622,0.163026,0.016926,0.040474,0.060104,0.187330,0.008186,0.019185,0.047349,-0.045320
EDUHIGHCAT,-0.617111,1.000000,-0.059258,-0.489276,0.046858,0.054705,0.044684,0.040900,0.014732,0.245745,...,0.138678,-0.055847,0.025940,0.097395,0.138991,-0.072085,0.025853,0.091311,0.095629,0.104966
EDUSCHLGO,0.051360,-0.059258,1.000000,0.186768,0.028624,0.015295,0.012048,0.010666,0.005496,-0.041474,...,0.009645,0.016120,-0.017704,0.004699,-0.002449,0.017556,-0.013433,-0.002500,-0.009013,0.002217
EDUSCHGRD2,0.631581,-0.489276,0.186768,1.000000,0.086930,0.031379,0.019098,0.017633,0.009889,-0.184386,...,-0.013887,0.109345,0.017007,0.026575,0.000793,0.127404,-0.014596,-0.026994,-0.028963,-0.053311
UADPAID,0.085338,0.046858,0.028624,0.086930,1.000000,0.716167,0.486879,0.451290,0.178556,0.060356,...,-0.047192,-0.102679,-0.063785,-0.091001,-0.095364,-0.145509,-0.019347,-0.013170,0.002237,-0.020553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TOBALCMN_MHTRTPY,0.187330,-0.072085,0.017556,0.127404,-0.145509,-0.052469,-0.030210,-0.028001,-0.007519,-0.202899,...,0.588787,0.843186,0.359142,0.493621,0.755300,1.000000,0.349140,0.579307,0.505662,0.593174
MHTRTPY_SMIPY,0.008186,0.025853,-0.013433,-0.014596,-0.019347,0.001894,0.011735,0.011449,0.004115,-0.054640,...,0.382706,0.397292,0.640463,0.291555,0.318717,0.349140,1.000000,0.591701,0.519860,0.448415
MHTRTPY_AMIPY,0.019185,0.091311,-0.002500,-0.026994,-0.013170,0.005092,0.008083,0.007690,0.005516,-0.040945,...,0.545824,0.669699,0.352597,0.482862,0.447581,0.579307,0.591701,1.000000,0.755055,0.757841
MHTRTPY_ATXMDEYR,0.047349,0.095629,-0.009013,-0.028963,0.002237,-0.002438,-0.001555,-0.002565,0.019856,0.025867,...,0.761611,0.627922,0.171583,0.101945,0.628709,0.505662,0.519860,0.755055,1.000000,0.782076
MHTRTPY_MHTRTPY,-0.045320,0.104966,0.002217,-0.053311,-0.020553,0.004080,0.006747,0.006255,0.005077,-0.018521,...,0.564588,0.703492,0.244425,0.301076,0.464306,0.593174,0.448415,0.757841,0.782076,1.000000

In [54]:
df_filter = df[comb_columns]
df_filter

,TOBFLAG_SMIPY,TOBFLAG_AMIPY,TOBFLAG_ATXMDEYR,TOBFLAG_MHTRTPY,TOBYR_SMIPY,TOBYR_AMIPY,TOBYR_ATXMDEYR,TOBYR_MHTRTPY,TOBMON_SMIPY,TOBMON_AMIPY,...,TOBALCYR_ATXMDEYR,TOBALCYR_MHTRTPY,TOBALCMN_SMIPY,TOBALCMN_AMIPY,TOBALCMN_ATXMDEYR,TOBALCMN_MHTRTPY,MHTRTPY_SMIPY,MHTRTPY_AMIPY,MHTRTPY_ATXMDEYR,MHTRTPY_MHTRTPY
0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
1,0.0,0.0,NaN,0,0.0,0.0,NaN,0,0.0,0.0,...,NaN,0,0.0,0.0,NaN,0,0.0,0.0,NaN,0
2,0.0,0.0,NaN,0,0.0,0.0,NaN,0,0.0,0.0,...,NaN,0,0.0,0.0,NaN,0,0.0,0.0,NaN,0
3,0.0,0.0,NaN,0,0.0,0.0,NaN,0,0.0,0.0,...,NaN,0,0.0,0.0,NaN,0,0.0,0.0,NaN,0
4,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30258,0.0,0.0,NaN,0,0.0,0.0,NaN,0,0.0,0.0,...,NaN,0,0.0,0.0,NaN,0,0.0,0.0,NaN,0
30259,0.0,0.0,NaN,0,0.0,0.0,NaN,0,0.0,0.0,...,NaN,0,0.0,0.0,NaN,0,0.0,0.0,NaN,0
30260,0.0,0.0,1.0,1,0.0,0.0,0.0,0,0.0,0.0,...,1.0,1,0.0,0.0,1.0,1,0.0,0.0,1.0,1
30261,0.0,1.0,1.0,1,0.0,0.0,0.0,0,0.0,0.0,...,1.0,1,0.0,1.0,1.0,1,0.0,1.0,1.0,1
30262,0.0,0.0,NaN,0,0.0,0.0,NaN,0,0.0,0.0,...,NaN,0,0.0,0.0,NaN,0,0.0,0.0,NaN,0

In [56]:
corr_matrix_filter = df_filter.corr()
corr_matrix_filter

,TOBFLAG_SMIPY,TOBFLAG_AMIPY,TOBFLAG_ATXMDEYR,TOBFLAG_MHTRTPY,TOBYR_SMIPY,TOBYR_AMIPY,TOBYR_ATXMDEYR,TOBYR_MHTRTPY,TOBMON_SMIPY,TOBMON_AMIPY,...,TOBALCYR_ATXMDEYR,TOBALCYR_MHTRTPY,TOBALCMN_SMIPY,TOBALCMN_AMIPY,TOBALCMN_ATXMDEYR,TOBALCMN_MHTRTPY,MHTRTPY_SMIPY,MHTRTPY_AMIPY,MHTRTPY_ATXMDEYR,MHTRTPY_MHTRTPY
TOBFLAG_SMIPY,1.000000,0.536969,0.437096,0.380765,0.750129,0.400075,0.339329,0.299836,0.613571,0.322288,...,0.222474,0.262358,0.780522,0.380648,0.233278,0.256169,0.621526,0.341282,0.159843,0.235755
TOBFLAG_AMIPY,0.536969,1.000000,0.544291,0.514279,0.402796,0.708441,0.370333,0.374602,0.329469,0.572974,...,0.207862,0.331984,0.398413,0.707353,0.236800,0.325793,0.297521,0.452147,0.088415,0.281725
TOBFLAG_ATXMDEYR,0.437096,0.544291,1.000000,0.764138,0.311482,0.317045,0.670653,0.491360,0.230553,0.223023,...,0.693073,0.493575,0.264613,0.255568,0.655973,0.467367,0.336736,0.426428,0.587807,0.435626
TOBFLAG_MHTRTPY,0.380765,0.514279,0.764138,1.000000,0.283461,0.349380,0.506944,0.706163,0.224674,0.265453,...,0.469966,0.724816,0.276334,0.335570,0.456107,0.693716,0.361199,0.554540,0.460183,0.565188
TOBYR_SMIPY,0.750129,0.402796,0.311482,0.283461,1.000000,0.568567,0.541525,0.430725,0.817954,0.458182,...,0.191525,0.217299,0.669405,0.336771,0.218429,0.228431,0.463183,0.253971,0.107232,0.175101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TOBALCMN_MHTRTPY,0.256169,0.325793,0.467367,0.693716,0.228431,0.274770,0.397094,0.583572,0.204804,0.237072,...,0.588787,0.843186,0.359142,0.493621,0.755300,1.000000,0.349140,0.579307,0.505662,0.593174
MHTRTPY_SMIPY,0.621526,0.297521,0.336736,0.361199,0.463183,0.221667,0.260047,0.285163,0.368752,0.172334,...,0.382706,0.397292,0.640463,0.291555,0.318717,0.349140,1.000000,0.591701,0.519860,0.448415
MHTRTPY_AMIPY,0.341282,0.452147,0.426428,0.554540,0.253971,0.306238,0.285616,0.403191,0.200972,0.231562,...,0.545824,0.669699,0.352597,0.482862,0.447581,0.579307,0.591701,1.000000,0.755055,0.757841
MHTRTPY_ATXMDEYR,0.159843,0.088415,0.587807,0.460183,0.107232,0.032407,0.388986,0.291863,0.067269,0.002999,...,0.761611,0.627922,0.171583,0.101945,0.628709,0.505662,0.519860,0.755055,1.000000,0.782076
MHTRTPY_MHTRTPY,0.235755,0.281725,0.435626,0.565188,0.175101,0.187508,0.286934,0.399115,0.137423,0.137829,...,0.564588,0.703492,0.244425,0.301076,0.464306,0.593174,0.448415,0.757841,0.782076,1.000000

In [58]:
columns = df.columns
columns

Index(['CATAGE', 'EDUHIGHCAT', 'EDUSCHLGO', 'EDUSCHGRD2', 'UADPAID', 'UADMONY',
       'UADBWHO', 'UADPLACE', 'UADBUND', 'TOBCIGONL',
       ...
       'TOBALCYR_ATXMDEYR', 'TOBALCYR_MHTRTPY', 'TOBALCMN_SMIPY',
       'TOBALCMN_AMIPY', 'TOBALCMN_ATXMDEYR', 'TOBALCMN_MHTRTPY',
       'MHTRTPY_SMIPY', 'MHTRTPY_AMIPY', 'MHTRTPY_ATXMDEYR',
       'MHTRTPY_MHTRTPY'],
      dtype='object', length=130)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30263 entries, 0 to 30262
Columns: 130 entries, CATAGE to MHTRTPY_MHTRTPY
dtypes: float64(75), int64(55)
memory usage: 30.0 MB

In [62]:
df.dtypes

CATAGE                int64
EDUHIGHCAT            int64
EDUSCHLGO             int64
EDUSCHGRD2            int64
UADPAID             float64
                     ...
TOBALCMN_MHTRTPY      int64
MHTRTPY_SMIPY       float64
MHTRTPY_AMIPY       float64
MHTRTPY_ATXMDEYR    float64
MHTRTPY_MHTRTPY       int64
Length: 130, dtype: object

In [63]:
use_columns

['TOBFLAG',
 'TOBYR',
 'TOBMON',
 'NICVAPFLAG',
 'NICVAPYR',
 'NICVAPMON',
 'TOBVNICFLAG',
 'TOBVNICYR',
 'TOBVNICMON',
 'COCYR',
 'COCMON',
 'ILLFLAG',
 'ILLMON',
 'ILLEMYR',
 'CDUFLAG',
 'DCIGMON',
 'BNGDRKMON',
 'HVYDRKMON',
 'TOBALCFLG',
 'TOBALCYR',
 'TOBALCMN',
 'MHTRTPY']

In [64]:
diag_columns

['SMIPY', 'AMIPY', 'ATXMDEYR', 'MHTRTPY']

In [65]:
comb_columns

['TOBFLAG_SMIPY',
 'TOBFLAG_AMIPY',
 'TOBFLAG_ATXMDEYR',
 'TOBFLAG_MHTRTPY',
 'TOBYR_SMIPY',
 'TOBYR_AMIPY',
 'TOBYR_ATXMDEYR',
 'TOBYR_MHTRTPY',
 'TOBMON_SMIPY',
 'TOBMON_AMIPY',
 'TOBMON_ATXMDEYR',
 'TOBMON_MHTRTPY',
 'NICVAPFLAG_SMIPY',
 'NICVAPFLAG_AMIPY',
 'NICVAPFLAG_ATXMDEYR',
 'NICVAPFLAG_MHTRTPY',
 'NICVAPYR_SMIPY',
 'NICVAPYR_AMIPY',
 'NICVAPYR_ATXMDEYR',
 'NICVAPYR_MHTRTPY',
 'NICVAPMON_SMIPY',
 'NICVAPMON_AMIPY',
 'NICVAPMON_ATXMDEYR',
 'NICVAPMON_MHTRTPY',
 'TOBVNICFLAG_SMIPY',
 'TOBVNICFLAG_AMIPY',
 'TOBVNICFLAG_ATXMDEYR',
 'TOBVNICFLAG_MHTRTPY',
 'TOBVNICYR_SMIPY',
 'TOBVNICYR_AMIPY',
 'TOBVNICYR_ATXMDEYR',
 'TOBVNICYR_MHTRTPY',
 'TOBVNICMON_SMIPY',
 'TOBVNICMON_AMIPY',
 'TOBVNICMON_ATXMDEYR',
 'TOBVNICMON_MHTRTPY',
 'COCYR_SMIPY',
 'COCYR_AMIPY',
 'COCYR_ATXMDEYR',
 'COCYR_MHTRTPY',
 'COCMON_SMIPY',
 'COCMON_AMIPY',
 'COCMON_ATXMDEYR',
 'COCMON_MHTRTPY',
 'ILLFLAG_SMIPY',
 'ILLFLAG_AMIPY',
 'ILLFLAG_ATXMDEYR',
 'ILLFLAG_MHTRTPY',
 'ILLMON_SMIPY',
 'ILLMON_AMIPY',
 'ILLMON_ATXMDEYR',
 'ILLMON_MHTRTPY',
 'ILLEMYR_SMIPY',
 'ILLEMYR_AMIPY',
 'ILLEMYR_ATXMDEYR',
 'ILLEMYR_MHTRTPY',
 'CDUFLAG_SMIPY',
 'CDUFLAG_AMIPY',
 'CDUFLAG_ATXMDEYR',
 'CDUFLAG_MHTRTPY',
 'DCIGMON_SMIPY',
 'DCIGMON_AMIPY',
 'DCIGMON_ATXMDEYR',
 'DCIGMON_MHTRTPY',
 'BNGDRKMON_SMIPY',
 'BNGDRKMON_AMIPY',
 'BNGDRKMON_ATXMDEYR',
 'BNGDRKMON_MHTRTPY',
 'HVYDRKMON_SMIPY',
 'HVYDRKMON_AMIPY',
 'HVYDRKMON_ATXMDEYR',
 'HVYDRKMON_MHTRTPY',
 'TOBALCFLG_SMIPY',
 'TOBALCFLG_AMIPY',
 'TOBALCFLG_ATXMDEYR',
 'TOBALCFLG_MHTRTPY',
 'TOBALCYR_SMIPY',
 'TOBALCYR_AMIPY',
 'TOBALCYR_ATXMDEYR',
 'TOBALCYR_MHTRTPY',
 'TOBALCMN_SMIPY',
 'TOBALCMN_AMIPY',
 'TOBALCMN_ATXMDEYR',
 'TOBALCMN_MHTRTPY',
 'MHTRTPY_SMIPY',
 'MHTRTPY_AMIPY',
 'MHTRTPY_ATXMDEYR',
 'MHTRTPY_MHTRTPY']

In [67]:
# Filter out columns in your dataframe
df_filtered = df[diag_columns + comb_columns]

# Compute the correlation matrix
correlation_matrix = df_filtered.corr()

# Extract correlations between use_columns and comb_columns
correlation_subset = correlation_matrix.loc[diag_columns, comb_columns]

# Display the correlation results
correlation_subset

,TOBFLAG_SMIPY,TOBFLAG_AMIPY,TOBFLAG_ATXMDEYR,TOBFLAG_MHTRTPY,TOBYR_SMIPY,TOBYR_AMIPY,TOBYR_ATXMDEYR,TOBYR_MHTRTPY,TOBMON_SMIPY,TOBMON_AMIPY,TOBMON_ATXMDEYR,TOBMON_MHTRTPY,NICVAPFLAG_SMIPY,NICVAPFLAG_AMIPY,NICVAPFLAG_ATXMDEYR,NICVAPFLAG_MHTRTPY,NICVAPYR_SMIPY,NICVAPYR_AMIPY,NICVAPYR_ATXMDEYR,NICVAPYR_MHTRTPY,NICVAPMON_SMIPY,NICVAPMON_AMIPY,NICVAPMON_ATXMDEYR,NICVAPMON_MHTRTPY,TOBVNICFLAG_SMIPY,TOBVNICFLAG_AMIPY,TOBVNICFLAG_ATXMDEYR,TOBVNICFLAG_MHTRTPY,TOBVNICYR_SMIPY,TOBVNICYR_AMIPY,TOBVNICYR_ATXMDEYR,TOBVNICYR_MHTRTPY,TOBVNICMON_SMIPY,TOBVNICMON_AMIPY,TOBVNICMON_ATXMDEYR,TOBVNICMON_MHTRTPY,COCYR_SMIPY,COCYR_AMIPY,COCYR_ATXMDEYR,COCYR_MHTRTPY,COCMON_SMIPY,COCMON_AMIPY,COCMON_ATXMDEYR,COCMON_MHTRTPY,ILLFLAG_SMIPY,ILLFLAG_AMIPY,ILLFLAG_ATXMDEYR,ILLFLAG_MHTRTPY,ILLMON_SMIPY,ILLMON_AMIPY,ILLMON_ATXMDEYR,ILLMON_MHTRTPY,ILLEMYR_SMIPY,ILLEMYR_AMIPY,ILLEMYR_ATXMDEYR,ILLEMYR_MHTRTPY,CDUFLAG_SMIPY,CDUFLAG_AMIPY,CDUFLAG_ATXMDEYR,CDUFLAG_MHTRTPY,DCIGMON_SMIPY,DCIGMON_AMIPY,DCIGMON_ATXMDEYR,DCIGMON_MHTRTPY,BNGDRKMON_SMIPY,BNGDRKMON_AMIPY,BNGDRKMON_ATXMDEYR,BNGDRKMON_MHTRTPY,HVYDRKMON_SMIPY,HVYDRKMON_AMIPY,HVYDRKMON_ATXMDEYR,HVYDRKMON_MHTRTPY,TOBALCFLG_SMIPY,TOBALCFLG_AMIPY,TOBALCFLG_ATXMDEYR,TOBALCFLG_MHTRTPY,TOBALCYR_SMIPY,TOBALCYR_AMIPY,TOBALCYR_ATXMDEYR,TOBALCYR_MHTRTPY,TOBALCMN_SMIPY,TOBALCMN_AMIPY,TOBALCMN_ATXMDEYR,TOBALCMN_MHTRTPY,MHTRTPY_SMIPY,MHTRTPY_AMIPY,MHTRTPY_ATXMDEYR,MHTRTPY_MHTRTPY
SMIPY,0.779754,0.374910,0.201207,0.256543,0.584916,0.281585,0.175535,0.207057,0.478435,0.226696,0.146191,0.166676,0.771483,0.370094,0.200897,0.261397,0.629330,0.304524,0.175226,0.213598,0.549322,0.268334,0.159761,0.194555,0.842576,0.402293,0.214477,0.272905,0.698249,0.332221,0.195574,0.235749,0.621796,0.296582,0.177932,0.214695,0.254457,0.136981,0.089775,0.109775,0.136333,0.068908,0.034415,0.058302,0.880071,0.431883,0.229897,0.304577,0.641231,0.323196,0.174067,0.237155,0.494347,0.260880,0.166372,0.203408,0.499398,0.249853,0.164602,0.189378,0.279896,0.142223,0.094118,0.124494,0.564695,0.250427,0.124166,0.167585,0.311169,0.146744,0.065022,0.093467,0.948739,0.452622,0.231144,0.301728,0.892811,0.414439,0.206028,0.275861,0.793919,0.361734,0.175641,0.242808,0.808828,0.445539,0.253542,0.309086
AMIPY,0.368994,0.687180,0.152970,0.301272,0.276793,0.486827,0.109628,0.224131,0.226404,0.393737,0.086202,0.175215,0.365081,0.679013,0.163928,0.299134,0.297811,0.527536,0.130071,0.235623,0.259949,0.449485,0.111171,0.207785,0.398723,0.765521,0.178202,0.327480,0.330425,0.603442,0.139430,0.262974,0.294246,0.525258,0.118343,0.232877,0.120414,0.188702,0.059868,0.100540,0.064515,0.104301,0.025767,0.060417,0.416466,0.794939,0.197948,0.367334,0.303443,0.524298,0.145996,0.263221,0.233934,0.380998,0.112474,0.209390,0.236325,0.398723,0.109122,0.195797,0.132452,0.215374,0.053837,0.113136,0.267224,0.492681,0.102890,0.205984,0.147251,0.250857,0.053103,0.110571,0.448961,0.910407,0.208845,0.383159,0.422495,0.850459,0.188719,0.359714,0.375697,0.732475,0.154569,0.309874,0.382752,0.646868,0.226265,0.400446
ATXMDEYR,0.157057,0.088846,0.638877,0.394351,0.111968,0.035278,0.428465,0.248451,0.073392,0.011370,0.328086,0.172995,0.153179,0.066592,0.629327,0.381510,0.107799,0.029370,0.468166,0.275074,0.099953,0.031048,0.397113,0.228441,0.175426,0.102845,0.720416,0.448171,0.135371,0.046907,0.539442,0.323419,0.108633,0.029391,0.457496,0.264485,0.047056,0.027303,0.168761,0.086993,-0.003943,-0.017512,0.076177,0.015064,0.208086,0.158142,0.785842,0.513884,0.127919,0.096573,0.492659,0.315917,0.108349,0.074716,0.355598,0.217425,0.079190,0.016617,0.339014,0.183772,0.048311,0.011373,0.182145,0.104971,0.094285,0.040069,0.435529,0.266426,0.016429,-0.009590,0.206615,0.100261,0.226064,0.185359,0.904673,0.598725,0.206760,0.148361,0.827128,0.541565,0.171558,0.108656,0.690232,0.434802,0.462076,0.660478,0.913790,0.675600
MHTRTPY,0.235755,0.281725,0.435626,0.565188,0.175101,0.187508,0.286934,0.399115,0.137423,0.137829,0.208791,0.312549,0.234355,0.268315,0.422019,0.594503,0.180429,0.199266,0.309067,0.473670,0.163778,0.177567,0.263003,0.389907,0.255755,0.309425,0.485066,0.662343,0.207336,0.227305,0.357569,0.526282,0.184897,0.196592,0.304115,0.441507,0.087639,0.091619,0.115688,0.154034,0.046549,0.050110,0.042511,0.081202,0.277630,0.347271,0.542013,0.682235,0.203859,0.242390,0.343689,0.450140,0.167945,0.194533,0.254404,0.346427,0.150059,0.158948,0.232658,0.307517,0.089910,0.079775,0.121848,0.159258,0.166201,0.190802,0.292736,0.403885,0.078385,0.091945,0.131434,0.200475,0.291160,0.372353,0.607413,0.755234,0.273908,0.350001,0.564588,0.703492,0.244425,0.301076,0.464306,0.593174,0.448415,0.757841,0.782076,1.000000